#!/bin/bash

case $1 in
    "start")
        cd /home/gmpvpc/gmpvpc-ble/dist/
        /usr/bin/node /home/gmpvpc/gmpvpc-ble/dist/index.js
    ;;
    "stop")
        PID=`pidof /usr/bin/node /home/gmpvpc/gmpvpc-ble/dist/index.js`
        kill -INT $PID
    ;;
    *)
        echo "Usage: gmpvpc {start|stop}"
        exit 1;
    ;;
esac
