---
- name: GMPVPC-3000
  hosts: rpi
  become: yes
  become_user: root

  tasks:
  - name: Install apt-transport-https
    apt:
      name: apt-transport-https
      state: latest

  - name: Add NodeJS GPG key
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present

  - name: Add NodeJS repository
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_8.x stretch main"

  - name: Add NodeJS source repository
    apt_repository:
      repo: "deb-src https://deb.nodesource.com/node_8.x stretch main"

  - name: Update APT repositories
    apt:
      update_cache: yes
      upgrade: dist

  - name: Install PostgreSQL
    apt:
      name: postgresql
      state: latest

  - name: Install NodeJS
    apt:
      name: nodejs
      install_recommends: yes
      state: latest

  - name: Install build essentials
    apt:
      name: build-essential
      install_recommends: yes
      state: latest

  - name: Install NPM
    apt:
      name: npm
      state: latest

  - name: Install InfluxDB
    apt:
      name: influxdb
      state: latest

  - name: Check that PostgreSQL is running
    systemd:
      name: postgresql
      state: started

  - name: Check that InfluxDB is running
    systemd:
      name: influxdb
      state: started

  - name: Create UNIX user named 'gmpvpc'
    user:
      name: gmpvpc
      state: present

  - name: checkout git repo
    become: no
    local_action:
      module: git
      repo: git@gmpvpc.ddns.net:gmpvpc/gmpvpc-ble.git
      dest: /tmp/gmpvpc-ble/

  - name: Push app to remote server
    synchronize:
      recursive: yes
      use_ssh_args: yes
      mode: push
      src: /tmp/gmpvpc-ble/
      dest: /home/gmpvpc/gmpvpc-ble/
      rsync_opts:
        - "--exclude=.git"
        - "--chown=gmpvpc:gmpvpc"

  - name: Run NPM install
    become: yes
    become_user: gmpvpc
    npm:
      path: /home/gmpvpc/gmpvpc-ble/

  - name: Build the app using 'npm run build'
    become: yes
    become_user: gmpvpc
    command: npm run build
    args:
      chdir: ~/gmpvpc-ble/

  - name: Push startup script
    synchronize:
      use_ssh_args: yes
      mode: push
      src: ./gmpvpcd
      dest: /usr/bin/
      rsync_opts:
        - "--chown=root:root"

  - name: Push service unit
    synchronize:
      use_ssh_args: yes
      mode: push
      src: ./gmpvpc.service
      dest: /etc/systemd/system/
      rsync_opts:
        - "--chown=root:root"

  - name: Enabling and starting service
    systemd:
      name: gmpvpc
      daemon_reload: yes
      enabled: yes
      state: started